language: c

addons:
  apt:
    packages:
      - doxygen

compiler:
  - gcc
  - clang

os:
  - linux
  - osx
  
script:
  - make
  - ./bootstrap && rm -rf build-autotools/ && mkdir build-autotools && cd build-autotools && ../configure && make && cd ..
  - ./bootstrap && rm -rf build-autotools/ && mkdir build-autotools && cd build-autotools && ../configure --enable-samples --enable-doc --with-ssl && make && cd ..

